import{chromium}from'playwright';
import assert from'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:'/usr/local/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.goto('http://127.0.0.1:4173/');await page.waitForFunction(()=>window.HanamiBackgroundUpdates);await page.evaluate(()=>{localStorage.setItem('hanami-library','[]');localStorage.setItem('hanami-categories',JSON.stringify([{id:'default',name:'Predeterminada',order:0}]));localStorage.setItem('hanami-smart-update-settings',JSON.stringify({restrictions:{},includeCategories:[],excludeCategories:[],refreshMetadata:false,showBadge:true}))});
await page.locator('[data-tab="more"]').click();await page.locator('[data-mt-open="background"]').click();assert(await page.getByText('Actualización en segundo plano',{exact:true}).count());assert(await page.getByText('Service Worker',{exact:false}).count());
await page.locator('[data-mt-bg-interval]').selectOption('24');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('hanami-background-interval'))),24);await page.locator('[data-mt-bg-restriction="unmetered"]').check();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('hanami-background-device-restrictions'))),['unmetered']);
await page.locator('[data-mt-bg-categories]').click();await page.locator('[data-mt-bg-category="default"]').selectOption('exclude');await page.locator('[data-mt-bg-categories-save]').click();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('hanami-smart-update-settings')).excludeCategories),['default']);
await page.evaluate(()=>window.HanamiBackgroundUpdates.syncState());const mirrored=await page.evaluate(async()=>{const db=await new Promise((ok,no)=>{const r=indexedDB.open('hanami-background-v1',1);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});return new Promise((ok,no)=>{const tx=db.transaction('state'),r=tx.objectStore('state').get('input');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})});assert.equal(mirrored.settings.interval,24);assert.deepEqual(mirrored.settings.excludeCategories,['default']);assert.deepEqual(mirrored.settings.deviceRestrictions,['unmetered']);
await page.locator('.mt-bg-action').click();await page.waitForFunction(()=>['success','partial','deferred','error'].includes(window.HanamiBackgroundUpdates.status().state),null,{timeout:10000});const status=await page.evaluate(()=>window.HanamiBackgroundUpdates.status());assert(['success','deferred'].includes(status.state),JSON.stringify(status));assert.deepEqual(errors,[]);await browser.close();console.log('PASS: mobile background screen persists schedule/constraints/categories, mirrors IDB and runs through the Service Worker');
