import{chromium}from'playwright';
import assert from'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:'/usr/local/bin/chromium',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.goto('http://127.0.0.1:4173/');
await page.evaluate(()=>{
  const manga={id:'swipe-manga',title:'Swipe nocturno',url:'/swipe-manga',sourceId:'test'};
  localStorage.setItem('hanami-library',JSON.stringify([{...manga,categories:['default'],favorite:true,totalChapters:1,unreadCount:1}]));
  localStorage.setItem('hanami-chapter-swipe-left',JSON.stringify('bookmark'));
  localStorage.setItem('hanami-chapter-swipe-right',JSON.stringify('read'));
  const emit=window.dispatchEvent.bind(window);window.dispatchEvent=event=>event.type==='hanami-library-change'?true:emit(event);
  document.querySelectorAll('main>section').forEach(section=>section.classList.add('hidden'));
  document.querySelector('#library').classList.remove('hidden');document.body.dataset.root='library';
  HanamiMangaDetail.mount(document.querySelector('#libraryRoot'),{manga,chapters:[{url:'/chapter-1',name:'Capítulo 1',number:1}],sourceId:'test',source:'Test',inLibrary:true,back(){},read(){}});
});
await page.locator('.md-chapter').waitFor({state:'visible'});
async function swipe(from,to){const row=page.locator('.md-chapter').first(),box=await row.boundingBox(),y=box.y+box.height/2;await row.dispatchEvent('pointerdown',{pointerId:7,pointerType:'touch',clientX:from,clientY:y,bubbles:true});for(let step=1;step<=8;step++)await row.dispatchEvent('pointermove',{pointerId:7,pointerType:'touch',clientX:from+(to-from)*step/8,clientY:y,bubbles:true});await row.dispatchEvent('pointerup',{pointerId:7,pointerType:'touch',clientX:to,clientY:y,bubbles:true});await page.waitForTimeout(240)}
await swipe(320,190);
let meta=await page.evaluate(()=>JSON.parse(localStorage.getItem('hanami-chapter-meta-/swipe-manga')));
assert.equal(meta[0].bookmark,true);
assert(await page.locator('.md-chapter.bookmarked').count());
await swipe(70,210);
meta=await page.evaluate(()=>JSON.parse(localStorage.getItem('hanami-chapter-meta-/swipe-manga')));
assert.equal(meta[0].read,true);
assert(await page.locator('.md-chapter.read').count());
const library=await page.evaluate(()=>JSON.parse(localStorage.getItem('hanami-library'))[0]);
assert.equal(library.unreadCount,0);
await page.locator('[data-tab="more"]').click();
await page.locator('[data-mt-open="settings"]').click();
await page.locator('[data-mt-setting="library"]').click();
assert.equal(await page.locator('[data-mt-chapter-swipe="left"]').inputValue(),'bookmark');
assert.equal(await page.locator('[data-mt-chapter-swipe="right"]').inputValue(),'read');
await page.locator('[data-mt-chapter-swipe="left"]').selectOption('disabled');
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('hanami-chapter-swipe-left'))),'disabled');
await page.evaluate(()=>{const manga={id:'swipe-manga',title:'Swipe nocturno',url:'/swipe-manga',sourceId:'test'};document.querySelector('#library').classList.remove('hidden');HanamiMangaDetail.mount(document.querySelector('#libraryRoot'),{manga,chapters:[{url:'/chapter-1',name:'Capítulo 1',number:1}],sourceId:'test',source:'Test',inLibrary:true,back(){},read(){}})});
await swipe(320,190);meta=await page.evaluate(()=>JSON.parse(localStorage.getItem('hanami-chapter-meta-/swipe-manga')));assert.equal(meta[0].bookmark,true);assert.equal(await page.locator('.md-chapter-swipe.ready').count(),0);
assert.deepEqual(errors,[]);
await browser.close();
console.log('PASS: mobile swipes toggle bookmark/read and Library settings persist each direction');
