import{chromium}from'playwright';import assert from'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:'/usr/local/bin/chromium',args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
const handler=route=>route.fulfill({status:200,contentType:'image/png',headers:{'content-length':String(png.length)},body:png});await page.route('**/cover-library.webp',handler);await page.route('**/cover-transient.webp',handler);
await page.addInitScript(()=>localStorage.setItem('hanami-library',JSON.stringify([{id:'cached',title:'Cached',url:'/m',sourceId:'test',favorite:true,categories:['default'],thumbnailUrl:'/cover-library.webp'}])));
await page.goto('http://127.0.0.1:4173/');assert(await page.evaluate(()=>HanamiCoverCache.warm('/cover-library.webp',{pinned:true})));assert(await page.evaluate(()=>HanamiCoverCache.warm('/cover-transient.webp')));await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();
let stats=await page.evaluate(()=>HanamiCoverCache.stats());assert.equal(stats.entries,2);assert.equal(stats.pinned,1);
await page.locator('[data-tab="more"]').click();await page.locator('[data-mt-open="data"]').click();await page.locator('[data-data-clear-covers]').click();assert.equal(await page.locator('[data-data-preserve-library]').isChecked(),true);await page.locator('[data-data-clear-covers-confirm]').click();await page.waitForFunction(async()=>{const value=await HanamiCoverCache.stats();return value.entries===1});stats=await page.evaluate(()=>HanamiCoverCache.stats());assert.equal(stats.entries,1);assert.equal(stats.pinned,1);
await page.unroute('**/cover-library.webp',handler);await page.unroute('**/cover-transient.webp',handler);await context.setOffline(true);const offline=await page.evaluate(()=>new Promise(resolve=>{const img=new Image;img.onload=()=>resolve(true);img.onerror=()=>resolve(false);img.src='/cover-library.webp?offline-check=1'.replace('?offline-check=1','');document.body.append(img)}));assert.equal(offline,true,'la portada de Biblioteca debe cargar desde Cache Storage sin red');assert.deepEqual(errors,[]);await browser.close();console.log('PASS: mobile UI preserves library covers and the service worker serves them offline');
