import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const files=['../public/index.html','../public/app.js','../public/browse-tab.css','../public/sw.js','../package.json'];
const [i,a,c,s,p]=await Promise.all(files.map(x=>readFile(new URL(x,import.meta.url),'utf8')));
assert(i.includes('id="exploreChrome"'));
assert(i.includes('id="browseAppbar" class="destination-appbar browse-appbar"'));
assert(i.includes('<h2>Explorar</h2>'));
assert(i.indexOf('id="browseAppbar"')<i.indexOf('id="exploreTabs"'));
for(const section of ['sources','extensions','migrate'])assert(i.includes(`data-browse-actions="${section}"`),section);
assert(!i.includes('<section id="sources" class="panel"><div class="toolbar">'));
assert(!i.includes('<section id="extensions" class="panel hidden"><div class="toolbar">'));
assert(!i.includes('<section id="migrate" class="panel hidden"><div class="toolbar">'));
assert(a.includes("$$('[data-browse-actions]').forEach"));
assert(a.includes("$('#exploreChrome').classList.add('hidden')"));
assert(c.includes('body[data-root="explore"]>.top,body[data-root="explore"] #hero{display:none!important}'));
assert(c.includes('.explore-chrome{position:sticky;top:0'));
assert(c.includes('.browse-appbar .browse-toolbar-actions'));
assert(c.includes('.explore-tabs{position:relative;top:auto'));
assert(s.includes('hanami-crimson-knot-v135'));
const pkg=JSON.parse(p);assert.equal(pkg.version,'5.9.0');assert(pkg.scripts.test.includes('explore-appbar-v85.test.mjs'));
console.log('PASS: Explore uses an Updates-style app bar, contextual actions and tabs without the Hanami header or hero');
