import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { inspectGithubStore } from '../api/index.mjs';
const payload={schema:'hanami-extension-store/v1',name:'Acme Hanami Store',badgeLabel:'COMMUNITY',contact:{website:'https://github.com/acme/hanami-store',discord:'https://discord.com/invite/acme'},extensions:[{id:'hanami.es.acme',name:'Acme',version:'1.2.0',lang:'es',runtime:'vercel-js',entry:'extensions/acme/index.mjs',manifest:'extensions/acme/manifest.json',operations:['popular','latest','search','details','chapters','pages'],sources:[{id:'hanami.es.acme',name:'Acme',lang:'es',baseUrl:'https://reader.example'}]}]};
let requested='';
const fetcher=async url=>{requested=url;return{ok:true,status:200,headers:{get:()=>null},text:async()=>JSON.stringify(payload)}};
const store=await inspectGithubStore('https://github.com/acme/hanami-store',fetcher);
assert.equal(requested,'https://raw.githubusercontent.com/acme/hanami-store/main/hanami-extension-store.json');
assert.equal(store.name,'Acme Hanami Store');assert.equal(store.contract,'hanami-extension-store/v1');
assert.equal(store.extensionCount,1);assert.equal(store.compatibleCount,1);assert.equal(store.adapters[0].runtime,'vercel-js');assert.equal(store.adapters[0].bundleUrl,'https://raw.githubusercontent.com/acme/hanami-store/main/extensions/acme/index.mjs');assert.equal(store.adapters[0].sources[0].runtime,'browser-worker');
await assert.rejects(()=>inspectGithubStore('http://127.0.0.1/private',fetcher),/github\.com/);
const files=['../public/app.js','../public/browse-tab.js','../public/browse-tab.css','../public/data-storage.js','../public/sw.js','../package.json'];
const [a,b,c,d,s,p]=await Promise.all(files.map(x=>readFile(new URL(x,import.meta.url),'utf8')));
for(const token of ['hanami-extension-stores','extensionStoresDialog','extensionStoreCreateDialog','extensionStoreConfirmDialog','addExtensionStore','deleteExtensionStore','refreshExtensionStores','copyExtensionStore','openExtensionStore','handleExtensionStoreDeepLink','data-extension-store-create','data-extension-store-confirm','data-extension-store-delete','data-extension-stores-refresh','rebuildExtensionCatalog'])assert(a.includes(token),token);
assert(b.includes('#browseChild [data-extension-store-card]')&&b.includes('URL del repositorio copiada'));
assert(c.includes('.extension-store-fab')&&c.includes('.extension-store-card')&&c.includes('@media(prefers-reduced-motion:reduce)'));
assert(d.includes("'hanami-extension-stores'"));
assert(s.includes('hanami-crimson-knot-v138'));
const pkg=JSON.parse(p);assert.equal(pkg.version,'5.12.0');assert(pkg.scripts.test.includes('extension-stores-github-v87.test.mjs'));
console.log('PASS: GitHub extension stores port includes safe inspection, create/confirm/delete dialogs, refresh, cards, backup and long-press copy');
