import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { fetchExtensionBundle, proxyExtensionRequest, fetchExtensionImage } from '../api/index.mjs';
const operations=['popular','latest','search','details','chapters','pages'];
const storeJson={schema:'hanami-extension-store/v1',name:'Worker Store',contact:{website:'https://github.com/acme/worker-store'},extensions:[{id:'hanami.es.worker',name:'Worker Source',version:'1.0.0',lang:'es',runtime:'vercel-js',entry:'extensions/worker/index.mjs',manifest:'extensions/worker/manifest.json',operations,sources:[{id:'hanami.es.worker',name:'Worker Source',lang:'es',baseUrl:'https://reader.example',hosts:['https://api.reader.example','https://cdn.reader.example'],imageHeaders:{Referer:'https://reader.example/'}}]}]};
const bundleCode=`export default {${operations.map(op=>`${op}:async()=>(${op==='pages'?'[]':'{}'})`).join(',')}}`;
const bundle=await fetchExtensionBundle('https://raw.githubusercontent.com/acme/worker-store/main/extensions/worker/index.mjs',async()=>({ok:true,status:200,headers:{get:()=>null},text:async()=>bundleCode}));
assert.equal(bundle.bytes,Buffer.byteLength(bundleCode));assert.match(bundle.sha256,/^[a-f0-9]{64}$/);
await assert.rejects(()=>fetchExtensionBundle('https://raw.githubusercontent.com/acme/worker-store/main/bad.mjs',async()=>({ok:true,status:200,headers:{get:()=>null},text:async()=>`import x from './x.mjs'; export default x`})),/autocontenido/);
const storeUrl='https://raw.githubusercontent.com/acme/worker-store/main/hanami-extension-store.json';
const fetcher=async url=>{const href=String(url);if(href===storeUrl)return{ok:true,status:200,headers:{get:()=>null},text:async()=>JSON.stringify(storeJson)};if(href==='https://api.reader.example/list')return{status:200,statusText:'OK',url:href,headers:{get:()=> 'application/json'},arrayBuffer:async()=>Buffer.from('{"ok":true}')};if(href==='https://cdn.reader.example/page.webp')return{ok:true,status:200,headers:{get:()=> 'image/webp'},arrayBuffer:async()=>Buffer.from('image')};throw Error('unexpected '+href)};
const proxied=await proxyExtensionRequest({storeUrl,extensionId:'hanami.es.worker',sourceId:'hanami.es.worker',url:'https://api.reader.example/list',method:'GET'},fetcher);
assert.equal(Buffer.from(proxied.body,'base64').toString(),'{"ok":true}');
await assert.rejects(()=>proxyExtensionRequest({storeUrl,extensionId:'hanami.es.worker',sourceId:'hanami.es.worker',url:'https://evil.example/list'},fetcher),/Host no declarado/);
const image=await fetchExtensionImage({storeUrl,extensionId:'hanami.es.worker',sourceId:'hanami.es.worker',url:'https://cdn.reader.example/page.webp'},fetcher);assert.equal(image.type,'image/webp');
const files=['../public/local-extensions.js','../public/app.js','../public/index.html','../public/sw.js','../docs/HANAMI_EXTENSION_DEVELOPMENT.md','../docs/examples/hanami-extension-store.json','../package.json'];
const [runtime,app,html,sw,guide,example,pkgText]=await Promise.all(files.map(x=>readFile(new URL(x,import.meta.url),'utf8')));
for(const token of ['indexedDB.open','new Worker','extension-bundle','extension-proxy','hanami-local-extensions','sha256','type:\'invoke\'','normalizeImages'])assert(runtime.includes(token),token);
for(const token of ['localExtensionTrustDialog','enableLocalExtension','HanamiLocalExtensions.invoke','HanamiLocalExtensions.disable','Confiar y habilitar'])assert(app.includes(token),token);
assert(html.includes('/local-extensions.js')&&sw.includes("'/local-extensions.js'"));
for(const token of ['Runtime descargable en el navegador','Web Worker','IndexedDB','permisos de red','Integridad opcional'])assert(guide.includes(token),token);
assert(Array.isArray(JSON.parse(example).extensions[0].sources));
assert(sw.includes('hanami-crimson-knot-v1354'));
const pkg=JSON.parse(pkgText);assert.equal(pkg.version,'5.9.4');assert(pkg.scripts.test.includes('local-browser-extensions-v89.test.mjs'));
console.log('PASS: external Hanami bundles download to IndexedDB, run in a Worker, use repository-verified hosts and enable without APK installation');
