import{chromium}from'playwright';import assert from'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:'/usr/local/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1024,height:768},hasTouch:true,isMobile:false});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{localStorage.setItem('hanami-tablet-ui-mode',JSON.stringify('automatic'));localStorage.setItem('hanami-background-status',JSON.stringify({newChapters:7,showBadge:true}));localStorage.setItem('hanami-library',JSON.stringify([]))});await page.goto('http://127.0.0.1:4173/');await page.waitForFunction(()=>document.body.classList.contains('nav-rail'));
const rail=await page.locator('.main-nav').evaluate(node=>{const r=node.getBoundingClientRect(),buttons=[...node.querySelectorAll('[data-tab]')].map(x=>x.getBoundingClientRect());return{x:r.x,y:r.y,width:r.width,height:r.height,xPositions:new Set(buttons.map(x=>Math.round(x.x))).size,yPositions:new Set(buttons.map(x=>Math.round(x.y))).size,label:node.getAttribute('aria-label'),display:getComputedStyle(node).display}});assert.equal(rail.x,0);assert.equal(rail.y,0);assert.equal(Math.round(rail.width),92);assert.equal(Math.round(rail.height),768);assert.equal(rail.xPositions,1);assert.equal(rail.yPositions,6);assert.equal(rail.label,'Navegación principal lateral');assert.equal(rail.display,'grid');
assert.equal(await page.locator('[data-tab="updates"] .nav-badge').textContent(),'7');await page.evaluate(()=>HanamiNavigation.setBadge('explore',3,'3 extensiones pendientes'));assert.equal(await page.locator('[data-tab="explore"] .nav-badge').getAttribute('aria-label'),'3 extensiones pendientes');
await page.locator('[data-tab="explore"]').focus();await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>document.activeElement?.dataset.tab),'more');await page.keyboard.press('Home');assert.equal(await page.evaluate(()=>document.activeElement?.dataset.tab),'library');
await page.locator('[data-tab="library"]').click();assert.equal(await page.locator('[data-tab="library"]').getAttribute('aria-current'),'page');await page.locator('[data-tab="library"]').click();await page.locator('.library-settings-dialog').waitFor();await page.locator('.dialog-x').click();
await page.locator('[data-tab="more"]').click();await page.locator('[data-tab="more"]').click();assert.equal(await page.locator('.main-nav').evaluate(node=>getComputedStyle(node).display),'grid','el rail permanece en sub-screens');await page.locator('[data-mt-setting="appearance"]').click();await page.locator('[data-mt-tablet-ui]').selectOption('never');await page.waitForFunction(()=>!document.body.classList.contains('nav-rail'));assert.equal(await page.locator('.main-nav').getAttribute('aria-label'),'Navegación principal inferior');await page.locator('[data-mt-tablet-ui]').selectOption('always');await page.waitForFunction(()=>document.body.classList.contains('nav-rail'));
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>HanamiNavigation.setTabletMode('automatic'));assert.equal(await page.evaluate(()=>document.documentElement.dataset.navigationSuite),'bar');await page.setViewportSize({width:844,height:390});await page.waitForFunction(()=>document.documentElement.dataset.navigationSuite==='rail');assert.deepEqual(errors,[]);await browser.close();console.log('PASS: tablet rail, modes, badges, reselect, keyboard and portrait/landscape switching work end-to-end');
