import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=name=>fs.readFileSync(new URL(name,import.meta.url),'utf8');
const manager=read('../public/download-manager.js'),app=read('../public/app.js'),library=read('../public/library.js'),detail=read('../public/manga-detail.js'),updates=read('../public/updates-tab.js'),more=read('../public/more-tab.js'),sw=read('../public/sw.js'),html=read('../public/index.html');
assert.match(manager,/indexedDB\.open\(DB_NAME,DB_VERSION\)/);
assert.match(manager,/caches\.open\(PAGE_CACHE\)/);
assert.match(manager,/AbortController/);
assert.match(manager,/state='downloaded'/);
assert.match(manager,/navigator\.storage\?\.persist/);
assert.match(manager,/loadPages/);
assert.doesNotMatch(detail,/setInterval\(\(\)=>\{if\(D\[i\]\?\.state!=='downloading'/);
assert.match(detail,/HanamiDownloads\?\.enqueue/);
assert.match(updates,/HanamiDownloads\?\.enqueue/);
assert.doesNotMatch(updates,/setTimeout\(\(\)=>downloadAction\(id,'complete'\),350\)/);
assert.match(more,/HanamiDownloads\?\.snapshot/);
assert.match(app,/HanamiDownloads\.loadPages/);
assert.match(library,/HanamiDownloads\.loadPages/);
assert.match(sw,/k!==PAGE_CACHE/);
assert.match(sw,/caches\.open\(PAGE_CACHE\)\.then\(c=>c\.match/);
assert.ok(html.indexOf('/download-manager.js')<html.indexOf('/reader.js'));
console.log('real downloads v94 regression tests passed');