import{chromium}from'playwright';import assert from'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:'/usr/local/bin/chromium',args:['--no-sandbox']});
async function setup(path='/library',viewport={width:390,height:844}){const context=await browser.newContext({viewport,hasTouch:true,isMobile:viewport.width<600}),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.route('**/api/**',route=>{const url=new URL(route.request().url()),p=url.pathname;if(p==='/api/sources')return route.fulfill({json:[{id:'s1',name:'Fuente prueba',lang:'es',baseUrl:'https://example.com',runtime:'web',status:'ready'}]});if(p==='/api/extensions')return route.fulfill({json:{items:[{id:'s1',name:'Extensión prueba',lang:'es',version:'1.0.0',runtime:'vercel-js',sourceIds:['s1']}]}});if(p.endsWith('/popular')||p.endsWith('/latest')||p.endsWith('/search'))return route.fulfill({json:{mangas:[{title:'Obra enlazada',url:'/work',thumbnailUrl:'/assets/fallen.webp'}]}});if(p.endsWith('/details'))return route.fulfill({json:{title:'Obra enlazada',url:'/work',description:'Detalle restaurado'}});if(p.endsWith('/chapters'))return route.fulfill({json:[{id:'c1',url:'/chapter-1',name:'Capítulo 1',number:1}]});if(p.endsWith('/pages'))return route.fulfill({json:[{imageUrl:'http://127.0.0.1:4173/assets/fallen.webp'}]});return route.fulfill({status:404,json:{error:'mock missing'}})});await page.addInitScript(()=>{localStorage.setItem('hanami-reduce-motion','true');localStorage.setItem('hanami-install-seeded','true');localStorage.setItem('hanami-installed-sources',JSON.stringify(['s1']));localStorage.setItem('hanami-library',JSON.stringify([{id:'m1',title:'Obra enlazada',url:'/work',sourceId:'s1',favorite:true,categories:['default'],thumbnailUrl:'/assets/fallen.webp',_chapters:[{id:'c1',url:'/chapter-1',name:'Capítulo 1',number:1}]}]))});await page.goto('http://127.0.0.1:4173'+path);await page.waitForFunction(()=>document.documentElement.dataset.hanamiReady==='true'&&window.HanamiScreenRestoration);return{context,page,errors}}
{
 const{context,page,errors}=await setup('/settings/reader');await page.waitForFunction(()=>HanamiScreens.current().type==='more-setting');const id=await page.evaluate(()=>HanamiScreens.current().id);await page.reload();await page.waitForFunction(()=>HanamiScreens.current().type==='more-setting'&&HanamiScreens.current().data.name==='reader');assert.equal(await page.evaluate(()=>HanamiScreens.current().id),id,'la recarga conserva la entrada actual');assert.equal(await page.locator('body').getAttribute('data-root'),'more');await page.goBack();await page.waitForFunction(()=>HanamiScreens.current().type==='root'&&document.body.dataset.root==='more');assert.deepEqual(errors,[]);await context.close()
}
{
 const{context,page,errors}=await setup('/search?q=Inicial');await page.waitForFunction(()=>HanamiScreens.current().type==='global-search');await page.locator('#globalQuery').fill('Consulta persistida');await page.waitForTimeout(180);await page.reload();await page.waitForFunction(()=>HanamiScreens.current().type==='global-search'&&document.querySelector('#globalQuery')?.value==='Consulta persistida');assert.equal(new URL(page.url()).searchParams.get('q'),'Consulta persistida');assert.deepEqual(errors,[]);await context.close()
}
{
 const{context,page,errors}=await setup('/manga/m1/chapter?chapter=%2Fchapter-1');await page.waitForFunction(()=>HanamiScreens.current().type==='reader');const id=await page.evaluate(()=>HanamiScreens.current().id);await page.reload();await page.waitForFunction(()=>HanamiScreens.current().type==='reader'&&!document.querySelector('#reader').classList.contains('hidden'));assert.equal(await page.evaluate(()=>HanamiScreens.current().id),id);assert((await page.locator('#readerChapter').textContent()).startsWith('Capítulo 1'));assert.deepEqual(errors,[]);await context.close()
}
{
 const{context,page,errors}=await setup('/explore');await page.locator('[data-open-source="s1"]').first().click();await page.waitForFunction(()=>HanamiScreens.current().type==='source');await page.locator('[data-manga="0"]').click();await page.waitForFunction(()=>HanamiScreens.current().type==='explore-detail');const id=await page.evaluate(()=>HanamiScreens.current().id);await page.reload();await page.waitForFunction(()=>HanamiScreens.current().type==='explore-detail'&&document.querySelector('#browseResults .mihon-detail'));assert.equal(await page.evaluate(()=>HanamiScreens.current().id),id);assert.deepEqual(errors,[]);await context.close()
}
{
 const{context,page,errors}=await setup('/library');await page.evaluate(()=>HanamiMigrationConfig.open(['m1']));await page.waitForFunction(()=>HanamiScreens.current().type==='migration-config');const id=await page.evaluate(()=>HanamiScreens.current().id);await page.reload();await page.waitForFunction(()=>HanamiScreens.current().type==='migration-config'&&document.querySelector('.migration-config-screen'));assert.equal(await page.evaluate(()=>HanamiScreens.current().id),id);assert.deepEqual(errors,[]);await context.close()
}
{
 const{context,page,errors}=await setup('/library',{width:1024,height:768});await page.locator('[data-lib-settings]').click();await page.waitForFunction(()=>document.querySelector('#modal').open);await page.reload();await page.waitForFunction(()=>document.body.classList.contains('nav-rail')&&HanamiScreens.current().type==='root');assert.equal(await page.locator('#modal').evaluate(node=>node.open),false,'los diálogos transitorios no reaparecen');assert.deepEqual(errors,[]);await context.close()
}
await browser.close();console.log('PASS: reload deterministically restores settings, search, reader, source detail and migration while dismissing transient dialogs');
