import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { inspectGithubStore } from '../api/index.mjs';
const response=value=>async()=>({ok:true,status:200,headers:{get:()=>null},text:async()=>JSON.stringify(value)});
const base={schema:'hanami-extension-store/v1',name:'Hanami Community',contact:{website:'https://github.com/acme/hanami'},extensions:[{id:'hanami.es.demo',name:'Demo',version:'1.0.0',lang:'es',runtime:'vercel-js',entry:'extensions/demo/index.mjs',manifest:'extensions/demo/manifest.json',operations:['popular','latest','search','details','chapters','pages'],sources:[{id:'hanami.es.demo',name:'Demo',lang:'es',baseUrl:'https://reader.example'}]}]};
const valid=await inspectGithubStore('https://raw.githubusercontent.com/acme/hanami/main/hanami-extension-store.json',response(base));
assert.equal(valid.contract,'hanami-extension-store/v1');assert.equal(valid.kind,'hanami-web');assert.equal(valid.compatibleCount,1);
await assert.rejects(()=>inspectGithubStore('https://raw.githubusercontent.com/acme/mihon/repo/index.min.json',response([{name:'Android',pkg:'x'}])),/requiere un objeto Hanami/);
await assert.rejects(()=>inspectGithubStore('https://raw.githubusercontent.com/acme/mihon/main/repo.json',response({...base,schema:undefined})),/falta schema/);
await assert.rejects(()=>inspectGithubStore('https://raw.githubusercontent.com/acme/apk/main/store.json',response({...base,extensions:[{...base.extensions[0],apkUrl:'https://x/app.apk'}]})),/Android\/APK/);
await assert.rejects(()=>inspectGithubStore('https://raw.githubusercontent.com/acme/kotlin/main/store.json',response({...base,extensions:[{...base.extensions[0],runtime:'android'}]})),/runtime debe ser/);
await assert.rejects(()=>inspectGithubStore('https://raw.githubusercontent.com/acme/partial/main/store.json',response({...base,extensions:[{...base.extensions[0],operations:['search']}]})),/operaciones web/);
const files=['../public/app.js','../api/index.mjs','../docs/HANAMI_EXTENSION_DEVELOPMENT.md','../docs/examples/hanami-extension-store.json','../public/sw.js','../package.json'];
const [app,api,guide,example,sw,pkgText]=await Promise.all(files.map(x=>readFile(new URL(x,import.meta.url),'utf8')));
for(const token of ['STORE_CONTRACT','REQUIRED_EXTENSION_OPERATIONS','hasAndroidFields','runtime debe ser','Repositorio incompatible'])assert(api.includes(token),token);
assert(app.includes('purgeIncompatibleExtensionStores')&&app.includes("contract==='hanami-extension-store/v1'"));
for(const token of ['Qué es una extensión Hanami','Contrato del adaptador','Contrato del repositorio','Descarga, confianza y ejecución','manga.genre','import()'])assert(guide.includes(token),token);
assert.equal(JSON.parse(example).schema,'hanami-extension-store/v1');
assert(sw.includes('hanami-group-library-parity-v125'));
const pkg=JSON.parse(pkgText);assert.equal(pkg.version,'5.8.58');assert(pkg.scripts.test.includes('strict-hanami-extension-contract-v88.test.mjs'));
console.log('PASS: Hanami strictly rejects Mihon/APK/mixed repositories and documents its vercel-js extension contract');
